import type { EdiTransactionSchema } from "../../schemaTypes";

// ST and the ISA/GS/GE/IEA envelope are generated by envelope.ts, not modeled here.
export const X12_850: EdiTransactionSchema = {
  standard: "X12",
  transactionCode: "850",
  name: "Purchase Order",
  header: [
    {
      tag: "BEG",
      name: "Beginning Segment",
      required: true,
      elements: [
        { id: "BEG01", name: "Transaction Set Purpose Code", position: 1, dataType: "ID", required: true, fixedValue: "00" },
        { id: "BEG02", name: "Purchase Order Type Code", position: 2, dataType: "ID", required: true, fixedValue: "NE" },
        { id: "BEG03", name: "Purchase Order Number", position: 3, dataType: "AN", maxLength: 22, required: true },
        { id: "BEG05", name: "Purchase Order Date", position: 5, dataType: "DT", required: true },
      ],
    },
    {
      tag: "N1",
      name: "Buyer Name",
      required: false,
      elements: [
        { id: "N101", name: "Entity ID Code", position: 1, dataType: "ID", required: true, fixedValue: "BY" },
        { id: "N102", name: "Buyer Name", position: 2, dataType: "AN", maxLength: 60, required: true },
      ],
    },
  ],
  bodyLoop: {
    id: "PO1Loop",
    repeating: true,
    segments: [
      {
        tag: "PO1",
        name: "Line Item",
        required: true,
        elements: [
          { id: "PO101", name: "Line Number", position: 1, dataType: "AN", required: true },
          { id: "PO102", name: "Quantity", position: 2, dataType: "N0", required: true },
          { id: "PO103", name: "Unit of Measure", position: 3, dataType: "ID", required: true },
          { id: "PO104", name: "Unit Price", position: 4, dataType: "N2", required: false },
          { id: "PO107", name: "Product ID Qualifier", position: 7, dataType: "ID", required: false, fixedValue: "VP" },
          { id: "PO108", name: "Product ID", position: 8, dataType: "AN", maxLength: 48, required: false },
        ],
      },
    ],
  },
  trailer: [
    {
      tag: "CTT",
      name: "Transaction Totals",
      required: false,
      elements: [{ id: "CTT01", name: "Number of Line Items", position: 1, dataType: "N0", required: true, derivedValue: "loopInstanceCount" }],
    },
    {
      tag: "SE",
      name: "Transaction Set Trailer",
      required: true,
      elements: [
        { id: "SE01", name: "Segment Count", position: 1, dataType: "N0", required: true, derivedValue: "segmentCount" },
        { id: "SE02", name: "Control Number", position: 2, dataType: "AN", required: true, derivedValue: "controlNumber" },
      ],
    },
  ],
};
